version: "3.8"
services:
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    networks:
      - app_network

  stomp-status-ping:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - APP_TESTING_PAGE_ENABLED=true
      - APP_AUTH_LOCAL=true
      - REDIS_HOST=redis

networks:
  app_network:
    driver: bridge