version: "3.8"
services:
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    profiles: [ dev ]

  rabbitmq:
    build:
      dockerfile: ./rabbitmq-stomp.Dockerfile
      context: .
    ports:
      - '15672:15672'
      - '61613:61613'
    profiles: [ dev ]