version: "3.8"
services:
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    build:
      dockerfile: ./rabbitmq-stomp.Dockerfile
      context: .
    ports:
      - '15672:15672'
      - '61613:61613'

  stomp-status-ping:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - APP_TESTING_PAGE_ENABLED=true
      - app.testing-page.stomp-url=ws://localhost:8080/stomp
      - APP_AUTH_LOCAL=true
      - REDIS_HOST=redis

networks:
  app_network:
    driver: bridge