spring:
  application:
    name: stomp-status-ping

  profiles:
    active: dev

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
      repository-type: indexed
  docker:
    compose:
      file: classpath:/docker-compose.yaml

app:
  websocket:
    stomp:
      server:
        endpoints: "/stomp"
        origins: "*"
        application-destination-prefix: "/app"
        principal-header: "Principal"
        principal-cookie: "principal"
        server-heartbeat: 10000
        client-heartbeat: 10000
      broker:
        destination:
          prefix: "/topic"
          user-status: "/status"

  redis:
    entity:
      active-ws-session:
        ttl: 60


server:
  servlet:
    session:
      timeout: 60

logging:
  level:
    root: info