spring:
  application:
    name: stomp-status-ping-dev

  docker:
    compose:
      enabled: true
      profiles:
        active: dev
      file: docker-compose.yaml

app:
  testing-page:
    enabled: true
  websocket:
    stomp:
      broker:
        external:
          enabled: true
      auth:
        local: true

logging:
  level:
    root: info