spring:
  application:
    name: stomp-status-ping

  profiles:
    active: ${APP_PROFILE:default}

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      password: ${REDIS_PASSWORD:}

app:
  testing-page:
    enabled: ${APP_TESTING_PAGE_ENABLED:false} # create endpoint to the testing page with a stomp client
    stomp-url: "ws://localhost:8080/stomp" # endpoint for websocket connections in the testing page. See: app.websocket.stomp.server.endpoints
  websocket:
    stomp:
      server:
        endpoints: ${APP_STOMP_ENDPOINT:/stomp} # endpoint for websocket connections to the application
        origins: "*"
        server-heartbeat: ${APP_SERVER_HEARTBEAT:10000}
        client-heartbeat: ${APP_CLIENT_HEARTBEAT:10000}
        destination:
          prefix: "/app"
          current-user-status: "/current-status" # stomp destination for retrieving user status without subscribing in the broker. Default: /app/current-status
      broker:
        external:
          enabled: ${APP_BROKER_ENABLED:true} # if true app will use an external broker. Otherwise, app will use an in-memory broker
          virtual-host: /
          relay-host: ${APP_BROKER_RELAY_HOST:localhost}
          relay-port: ${APP_BROKER_RELAY_PORT:61613}
          client-login: ${APP_BROKER_CLIENT_LOGIN:guest}
          client-passcode: ${APP_BROKER_CLIENT_PASSCODE:guest}
          system-login: guest
          system-passcode: guest
          heartbeat-send-interval: 10000
          heartbeat-receive-interval: 10000
        destination:
          prefix: "/topic"
          user-status: "/status" # stomp destination to subscribe to user status changing. Default: /topic/status
      auth:
        local: ${APP_AUTH_LOCAL:false} # if false app will use external authentication service. See: app.webclient.auth
        username-header: ${APP_AUTH_USERNAME_HEADER:username}
        token-header: ${APP_AUTH_TOKEN_HEADER:token}
        token-cookie: token
  webclient:
    auth:
      write-timeout: 3000
      read-timeout: 3000
      connect-timeout: 3000
      base-url: ${APP_AUTH_REMOTE_BASE_URL:http://localhost:8082}
      auth-path: ${APP_AUTH_REMOTE_AUTH_PATH:/auth/chatAuth}
      auth-response-timeout: 5000
      token-header: ${APP_AUTH_REMOTE_TOKEN_HEADER:Authorization}
      response-username-field: "nickname" # username path in json response from auth service. Example: outerField/../username. Default: nickname

  redis:
    entity:
      active-ws-session:
        ttl: ${APP_REDIS_SESSION_TTL:60}

server:
  servlet:
    session:
      timeout: ${APP_SERVLET_SESSION_TIMEOUT:60}
  port: ${SEVER_PORT:8080}
  address: 0.0.0.0

logging:
  level:
    root: ${APP_LOGGING_LEVEL:info}