spring:
  application:
    name: stomp-status-ping

  profiles:
    active: dev

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
      repository-type: indexed
  docker:
    compose:
      file: classpath:/docker-compose.yaml

app:
  websocket:
    stomp:
      server:
        endpoints: "/stomp"
        application-destination-prefixes: "/app"
        broker-destination-prefixes: "/topic"
        principal-header: "Principal"
        principal-cookie: "principal"
        heartbeat-time: 25000


server:
  servlet:
    session:
      timeout: 60

logging:
  level:
    root: info