spring:
  application:
    name: stomp-status-ping

  profiles:
    active: ${APP_PROFILE}

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}

app:
  testing-page:
    enabled: ${APP_TESTING_PAGE_ENABLED:false}
  websocket:
    stomp:
      server:
        endpoints: ${APP_STOMP_ENDPOINT:/stomp}
        origins: "*"
        server-heartbeat: ${APP_SERVER_HEARTBEAT:10000}
        client-heartbeat: ${APP_CLIENT_HEARTBEAT:10000}
        destination:
          prefix: "/app"
          current-user-status: "/current-status"
      broker:
        destination:
          prefix: "/topic"
          user-status: "/status"
      auth:
        local: ${APP_AUTH_LOCAL:false}
        username-header: ${APP_AUTH_USERNAME_HEADER:username}
        token-header: ${APP_AUTH_TOKEN_HEADER:token}
  webclient:
    auth:
      write-timeout: 3000
      read-timeout: 3000
      connect-timeout: 3000
      base-url: ${APP_AUTH_REMOTE_BASE_URL:http://localhost:8082}
      auth-path: ${APP_AUTH_REMOTE_AUTH_PATH:/auth/chatAuth}
      auth-response-timeout: 5000
      token-header: ${APP_AUTH_REMOTE_TOKEN_HEADER:Authorization}

  redis:
    entity:
      active-ws-session:
        ttl: ${APP_REDIS_SESSION_TTL:60}


server:
  servlet:
    session:
      timeout: ${APP_SERVLET_SESSION_TIMEOUT:60}

logging:
  level:
    root: ${APP_LOGGING_LEVEL:info}