spring:
  application:
    name: stomp-status-ping-dev

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  docker:
    compose:
      enabled: true
      profiles:
        active: dev

app:
  testing-page:
    enabled: true
  websocket:
    stomp:
      auth:
        local: true

logging:
  level:
    root: debug