spring:
  application:
    name: stomp-status-ping

  profiles:
    active: ${APP_PROFILE:default}

  docker:
    compose:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
      password: ${REDIS_PASSWORD:}

app:
  testing-page:
    enabled: ${APP_TESTING_PAGE_ENABLED:false}
    stomp-url: "ws://localhost:8080/stomp"
  websocket:
    stomp:
      server:
        endpoints: ${APP_STOMP_ENDPOINT:/stomp}
        origins: "*"
        server-heartbeat: ${APP_SERVER_HEARTBEAT:10000}
        client-heartbeat: ${APP_CLIENT_HEARTBEAT:10000}
        destination:
          prefix: "/app"
          current-user-status: "/current-status"
      broker:
        external:
          enabled: ${APP_BROKER_ENABLED:false}
          virtual-host: /
          relay-host: ${APP_BROKER_RELAY_HOST:localhost}
          relay-port: ${APP_BROKER_RELAY_PORT:61613}
          client-login: ${APP_BROKER_CLIENT_LOGIN:guest}
          client-passcode: ${APP_BROKER_CLIENT_PASSCODE:guest}
          system-login: guest
          system-passcode: guest
          heartbeat-send-interval: 10000
          heartbeat-receive-interval: 10000
        destination:
          prefix: "/topic"
          user-status: "/status"
      auth:
        local: ${APP_AUTH_LOCAL:false}
        username-header: ${APP_AUTH_USERNAME_HEADER:username}
        token-header: ${APP_AUTH_TOKEN_HEADER:token}
  webclient:
    auth:
      write-timeout: 3000
      read-timeout: 3000
      connect-timeout: 3000
      base-url: ${APP_AUTH_REMOTE_BASE_URL:http://localhost:8082}
      auth-path: ${APP_AUTH_REMOTE_AUTH_PATH:/auth/chatAuth}
      auth-response-timeout: 5000
      token-header: ${APP_AUTH_REMOTE_TOKEN_HEADER:Authorization}

  redis:
    entity:
      active-ws-session:
        ttl: ${APP_REDIS_SESSION_TTL:60}

server:
  servlet:
    session:
      timeout: ${APP_SERVLET_SESSION_TIMEOUT:60}
  port: ${SEVER_PORT:8081}
  address: 0.0.0.0

logging:
  level:
    root: ${APP_LOGGING_LEVEL:info}